apiVersion: batch/v1
kind: Job
metadata:
  name: hellok8s-job
spec:
  parallelism: 3 ## 并行数量
  completions: 5 ## 需要完成数量
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: echo
          image: busybox
          command: 
            - "sh"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"